baseURL = 'https://adinack.dev/'
languageCode = 'en-us'
title = 'Personal Site'
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = ["hugo-video"]

[menus]

[[menus.main]]
name = 'projects'
pageRef = '/projects'
weight = 1

[[menus.main]]
name = 'blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'interests'
pageRef = '/interests'
weight = 3

[[menus.main]]
name = 'me'
pageRef = '/me'
weight = 4
